apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubescape-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/kubescape-data"
